feat/icrc-2-integration-and ICRC-1-enhancements
Jair-SDS/wallet pull request #24
Opened 2024-01-15 15:24 UTC by JulioSDS

# ICRC 2 Integration and ICRC 1 Enhancements

This pull request introduces ICRC 2 functionality and enhances existing ICRC 1 features, enabling:

- Transaction management: Approve and manage ICRC 2 transactions
- Allowance management: View and manage allowances granted to you or created by you
- Expanded transfer options: Transfer funds from various sources and to different destinations

## Key Features

- Enhanced Contact Book: See contacts who granted you allowances
- Allowance Management UI: Easily view and manage created and received allowances
- Flexible Transfers: Transfer funds from subaccounts, allowances, and to own account or third parties

## Addtional notes

- [ICRC-2](https://github.com/dfinity/ICRC-1/blob/main/standards/ICRC-2/README.md)

2024-01-15 15:40 UTC, OliverSDSharp requested changes

2024-01-15 15:40 UTC, OliverSDSharp commented on frontend/helpers/icrc.ts
> +  console.log(newSubAccounts);
delete

2024-01-15 15:40 UTC, OliverSDSharp commented on frontend/pages/contacts/components/AddContact/SubAccountFormItem.tsx
> +  function isAvailableAddContact() {
can we reduce this component? maybe put those functions on other file or hook?

2024-01-15 15:40 UTC, OliverSDSharp commented on frontend/pages/contacts/components/addContact.tsx
> +  async function onAllowanceNewContactCheck() {
lets reduce this components size. too big with many funcionalities. lets move all functions to a hook.

2024-01-15 15:40 UTC, OliverSDSharp commented on frontend/pages/contacts/components/tableSubAccounts.tsx
> +  async function checkSubAcc(edit: boolean, cntc: Contact, asst: AssetContact, sa?: SubAccountContact) {
lets also reduce the size of this component. moving logic to other file.

2024-01-15 15:40 UTC, OliverSDSharp commented on frontend/redux/CheckAuth.tsx
> +  console.log(principal);
delete

2024-01-15 16:02 UTC, JulioSDS commented on frontend/pages/contacts/components/AddContact/SubAccountFormItem.tsx
> +  function isAvailableAddContact() {
Done

2024-01-15 16:02 UTC, JulioSDS commented on frontend/helpers/icrc.ts
> +  console.log(newSubAccounts);
Done

2024-01-15 17:16 UTC, Julio-SDSharp commented on frontend/pages/contacts/components/addContact.tsx
> +  async function onAllowanceNewContactCheck() {
done

2024-01-15 21:24 UTC, JulioSDS commented on frontend/pages/contacts/components/tableSubAccounts.tsx
> +  async function checkSubAcc(edit: boolean, cntc: Contact, asst: AssetContact, sa?: SubAccountContact) {
done

2024-01-16 11:16 UTC, JulioSDS commented on frontend/redux/CheckAuth.tsx
> +  console.log(principal);
Done

2024-02-01 18:33 UTC, OliverSDS requested changes

2024-02-01 18:33 UTC, OliverSDSharp commented on frontend/components/modal/Modal.tsx
> +              className={`bg-RadioCheckColor rounded-lg py-2 flex justify-center items-center ${
on this type of validations. use clxc. becuase this adds empty space to the class string

2024-02-01 18:33 UTC, OliverSDSharp commented on frontend/pages/contacts/components/AddContact/AddAssetOnCreate.tsx
> +        {assets.filter((ast) => {
maybe is best to place this o a usememo that way wont compute on each re-render.

2024-02-01 18:33 UTC, OliverSDSharp commented on frontend/pages/contacts/components/contactAssetPop.tsx
> +              className={`h-[2rem] rounded-r-sm w-7 grid place-items-center ${
change for clxs

2024-02-01 18:33 UTC, OliverSDSharp commented on frontend/pages/contacts/components/tableContacts.tsx
>    function getContactsToShow() {
too much functions on component. maybe the best is to add them to the hook?

2024-02-01 18:33 UTC, OliverSDSharp commented on frontend/pages/home/components/ICRC/detail/transaction/SendForm/AllowanceContactBook.tsx
> +      <DropdownMenu.Root modal={isOpen} onOpenChange={onOpenChange}>
(i cannot add it to folder) lets split that many files, into diferent folders maybe. i see sender, receiver, contacts componets. all can be organized better.

2024-02-01 18:33 UTC, OliverSDS commented on frontend/pages/home/components/ICRC/detail/transaction/SendForm/ReceiverOwnerOld.tsx
> +            {contactToSend
to complicated. lets avoid big ternary. can be on a function?

2024-02-01 18:33 UTC, OliverSDS commented on frontend/pages/home/components/ICRC/detail/transaction/SendForm/ReceiverOwnerOld.tsx
> +        {!maxAmount().valid ? (
too complex with ternaries. lets put it on a function

2024-02-01 18:33 UTC, OliverSDS commented on frontend/pages/home/components/ICRC/detail/transaction/SendForm/ReceiverType.tsx
> +      <p className="font-bold opacity-50 text-PrimaryTextColorLight dark:text-PrimaryTextColor text-md">To</p>
translation

2024-02-01 18:33 UTC, OliverSDS commented on frontend/redux/Store.ts
> +  devTools: true,
this does not go to dev/main

2024-02-02 16:20 UTC, OliverSDS requested changes

2024-02-02 16:20 UTC, OliverSDSharp commented on frontend/defaultTokens.ts
> +    supportedStandards: [SupportedStandardEnum.Values["ICRC-1"], SupportedStandardEnum.Values["ICRC-2"]],
If is all the same why not just 1 variable and put in on each supportedStandars?

2024-02-02 16:37 UTC, OliverSDS approved these changes

2024-02-02 16:38 UTC, merged