feat: login with a principal and anonymous identity
Jair-SDS/wallet pull request #27
Opened 2024-01-17 19:26 UTC by lllarghi

#25

2024-01-18 13:54 UTC, OliverSDS requested changes

2024-01-18 13:54 UTC, OliverSDS commented on frontend/pages/components/topbar/index.tsx
> +            {watchOnlyMode && <p className="opacity-50">Watch-Only Mode</p>}
add translation please.

2024-01-18 13:54 UTC, OliverSDS commented on frontend/pages/home/components/ICRC/detail/SubaccountAction.tsx
> +            className={`flex flex-row justify-center items-center w-7 h-7 rounded-md cursor-pointer ${
on this validations is best to use clsx because avoids empty spaces

2024-01-18 14:00 UTC, LuiLar commented on frontend/pages/home/components/ICRC/detail/SubaccountAction.tsx
> +            className={`flex flex-row justify-center items-center w-7 h-7 rounded-md cursor-pointer ${
Never use CLSX lib before, going to try it now.

2024-01-19 14:03 UTC, OliverSDS approved these changes

2024-01-19 14:31 UTC, merged