Fix/assets tokens data duplication
Jair-SDS/wallet pull request #65
Opened 2024-04-05 12:21 UTC by JulioSDSharp

2024-04-11 20:48 UTC, Jair-MoralesN commented
All functionality 100% working correctly

2024-04-15 12:21 UTC, OliverSDSharp requested changes

2024-04-15 12:21 UTC, OliverSDSharp commented on canisters/database/main.mo
>    /**
Do we need it commented?

2024-04-15 13:01 UTC, JulioSDSharp commented on canisters/database/main.mo
>    /**
Not at all, comment removed.

2024-04-15 18:09 UTC, merged